version: '3.8'

services:
  web:
    build: .
    container_name: vulnhotel_web
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    restart: unless-stopped

  db:
    image: mysql:5.7
    container_name: vulnhotel_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: vulnhotel
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./vulnhotel.sql:/docker-entrypoint-initdb.d/vulnhotel.sql

volumes:
  db_data:

